name: spritewidget
description: SpriteWidget is an open source toolkit for building complex, high performance animations and 2D games with Flutter.
version: 2.0.1

homepage: https://spritewidget.com/
repository: https://github.com/spritewidget/spritewidget/
issue_tracker: https://github.com/spritewidget/spritewidget/issues

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.1

dev_dependencies:
  flutter_lints: ^5.0.0